---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: truck-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: truck-frontend-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: truck-frontend-deployment
    spec:
      containers:
        - name: truck-backend
          image: docker.io/lehnerj/lehnerj:spring-sample-truck-frontend
          env:
            - name: TRUCK_TARGETENDPOINT
              value: truck-restfacade-service:8081