---
apiVersion: v1
kind: Service
metadata:
  name: truck-frontend-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: truck-frontend-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: truck-restfacade-service
spec:
  selector:
    app.kubernetes.io/name: truck-restfacade-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: truck-backend-service
spec:
  selector:
    app.kubernetes.io/name: truck-backend-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: truck-truckdb-service
spec:
  selector:
    app.kubernetes.io/name: truck-truckdb-deployment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: truck-auditdb-service
spec:
  selector:
    app.kubernetes.io/name: truck-auditdb-deployment
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 3306