---
# DO NOT USE THIS IN PRODUCTION
apiVersion: apps/v1
kind: Deployment
metadata:
  name: truck-truckdb-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: truck-truckdb-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: truck-truckdb-deployment
    spec:
      containers:
        - image: mysql
          name: mysql
          env:
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: dbuser
            - name: MYSQL_DATABASE
              value: truckdb
          ports:
            - containerPort: 3306
              name: mysql